/*----------------------------------------------------------------
    Copyright (C) 2026 Senparc

    文件名：20260918120000_AddAliasAndExtraPorts.Designer.cs
    文件功能描述：数据库迁移与模型快照


    创建标识：Senparc - 20260918

    修改标识：Senparc - 20260918
    修改描述：v0.3.3 增加沙箱会话别名与附加端口映射列

----------------------------------------------------------------*/

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Senparc.Xncf.Sandbox.Models;

#nullable disable

namespace Senparc.Xncf.Sandbox.Domain.Migrations.PostgreSQL
{
    [DbContext(typeof(SandboxSenparcEntities_PostgreSQL))]
    [Migration("20260918120000_AddAliasAndExtraPorts")]
    partial class AddAliasAndExtraPorts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

                        modelBuilder.Entity("Senparc.Xncf.Sandbox.Domain.Models.DatabaseModel.SandboxSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(128)
                        .HasColumnType("text");

                    b.Property<string>("AccessUrl")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(300)
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .HasMaxLength(128)
                        .HasColumnType("text");


                    b.Property<double>("CpuLimit")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExtraPorts")
                        .HasMaxLength(500)
                        .HasColumnType("text");


                    b.Property<bool>("Flag")
                        .HasColumnType("boolean");

                    b.Property<int?>("HostPort")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MemoryMb")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .HasColumnType("text");

                    b.Property<string>("RuntimeHandle")
                        .HasMaxLength(128)
                        .HasColumnType("text");

                    b.Property<int>("RuntimeKind")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Status");

                    b.ToTable("Senparc_Sandbox_SandboxSession");
                });
#pragma warning restore 612, 618
        }
    }
}
