<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.0.4</Version>
    <PackageReleaseNotes>
      [2026-07-17] v0.0.1 同步上游项目版本并适配统一本地化能力
      1、Dependency update from Senparc.Ncf.Core to 0.25.0-preview2
      2、Dependency update from Senparc.Ncf.XncfBase to 0.23.3-preview2
      [2026-07-29] v0.0.2 Dependency update from Senparc.Ncf.Core to 0.26.0-preview3
      [2026-07-31] v0.0.3 Dependency update from Senparc.Ncf.Core to 0.27.0-preview4
      [2026-08-04] v0.0.4 Dependency updates from upstream projects
      1、Dependency update from Senparc.Ncf.Core to 0.28.0-preview5
      2、Dependency update from Senparc.Ncf.XncfBase to 0.24.0-preview5
    </PackageReleaseNotes>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Basic\Senparc.Ncf.Core\Senparc.Ncf.Core.csproj" />
    <ProjectReference Include="..\..\Basic\Senparc.Ncf.XncfBase\Senparc.Ncf.XncfBase.csproj" />
  </ItemGroup>

</Project>
