/*----------------------------------------------------------------
    Copyright (C) 2026 Senparc

    文件名：20260802183821_Add_XncfPreview.Designer.cs
    文件功能描述：定义 Entity Framework 数据库迁移元数据。


    创建标识：Senparc - 20231021

    修改标识：Senparc - 20260804
    修改描述：v0.39.0-preview8 新增 XNCF 隔离预览持久化与跨数据库迁移支持

----------------------------------------------------------------*/

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senparc.Xncf.XncfBuilder.Models.MultipleDatabase;

#nullable disable

namespace Senparc.Xncf.XncfBuilder.Domain.Migrations.Dm
{
    [DbContext(typeof(XncfBuilderSenparcEntities_Dm))]
    [Migration("20260802183821_Add_XncfPreview")]
    partial class Add_XncfPreview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Senparc.Xncf.XncfBuilder.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<bool>("Flag")
                        .HasColumnType("BIT");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("MenuName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("OrgName")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("SlnFilePath")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<int>("TenantId")
                        .HasColumnType("INT");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("XncfName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.ToTable("XncfBuilderConfig");
                });

            modelBuilder.Entity("Senparc.Xncf.XncfBuilder.XncfPreviewHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("EnvironmentName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INT");

                    b.Property<bool>("Flag")
                        .HasColumnType("BIT");

                    b.Property<DateTime?>("HealthyAtUtc")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ModuleProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("ProcessStartedAtUtc")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("PublishDirectory")
                        .HasMaxLength(1200)
                        .HasColumnType("NVARCHAR2(1200)");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("TenantId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.ToTable("XncfBuilderXncfPreviewHost");
                });

            modelBuilder.Entity("Senparc.Xncf.XncfBuilder.XncfPreviewTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("CLOB");

                    b.Property<bool>("Flag")
                        .HasColumnType("BIT");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ModuleAssemblySha256")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<string>("ModuleProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INT");

                    b.Property<string>("RecentOutput")
                        .HasColumnType("CLOB");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("SolutionFilePath")
                        .HasMaxLength(1200)
                        .HasColumnType("NVARCHAR2(1200)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<int>("Stage")
                        .HasColumnType("INT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("TenantId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("ModuleProjectName", "StartedAtUtc");

                    b.ToTable("XncfBuilderXncfPreviewTask");
                });
#pragma warning restore 612, 618
        }
    }
}
