// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Senparc.Xncf.Sandbox.Models;

#nullable disable

namespace Senparc.Xncf.Sandbox.Domain.Migrations.Oracle
{
    [DbContext(typeof(SandboxSenparcEntities_Oracle))]
    [Migration("20240423143234_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

                        modelBuilder.Entity("Senparc.Xncf.Sandbox.Domain.Models.DatabaseModel.SandboxSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AccessUrl")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("CpuLimit")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("Flag")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("HostPort")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("MemoryMb")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RuntimeHandle")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RuntimeKind")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TenantId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Status");

                    b.ToTable("Senparc_Sandbox_SandboxSession");
                });
#pragma warning restore 612, 618
        }
    }
}
