<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Version>0.1.0</Version>
    <PackageReleaseNotes>
      [2026-07-17] v0.1.0 为 Application 模块接入统一资源本地化并优化功能文案
      1、接入统一资源本地化机制，支持模块功能文案按当前文化动态显示
      2、统一模块注册信息、菜单名称与功能描述的本地化输出
      3、补充并统一多语言资源键及资源文件
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Basic\Senparc.Ncf.XncfBase\Senparc.Ncf.XncfBase.csproj" />
  </ItemGroup>

</Project>
