// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senparc.Xncf.FirmwareUpdate.Models;

#nullable disable

namespace Senparc.Xncf.FirmwareUpdate.Domain.Migrations.MySql;

[DbContext(typeof(FirmwareUpdateSenparcEntities_MySql))]
[Migration("20260504120000_Init")]
partial class Init
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("Senparc.Xncf.FirmwareUpdate.FirmwareUpdateConfig", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("AddTime")
                    .HasColumnType("datetime(6)");

                b.Property<bool>("AutoMirrorEnabled")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("AdminRemark")
                    .HasMaxLength(300)
                    .HasColumnType("varchar(300)");

                b.Property<bool>("Flag")
                    .HasColumnType("tinyint(1)");

                b.Property<DateTime?>("LastPeriodicSyncUtc")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("LastUpdateTime")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Remark")
                    .HasMaxLength(300)
                    .HasColumnType("varchar(300)");

                b.Property<int>("TenantId")
                    .HasColumnType("int");

                b.Property<int>("UpdateIntervalHours")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Senparc_FirmwareUpdate_FirmwareUpdateConfig");
            });
#pragma warning restore 612, 618
    }
}
