using Microsoft.CodeAnalysis.CSharp.Syntax;
using Senparc.CO2NET;
using Senparc.CO2NET.Extensions;
using Senparc.CO2NET.WebApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Senparc.Ncf.Core.WebApi
{
    public static class NcfWebApiHelper
    {
        /// <summary>
        /// Get the web API address generated by XNCF and [ApiBind] features
        /// </summary>
        /// <param name="xncfName">XNCF assembly name (usually the same name as XNCF)</param>
        /// <param name="appServiceName">AppService name or Controller name (called category in [ApiBind])</param>
        /// <param name="methodName">Method name or defined API name (called `name` in [ApiBind])</param>
        /// <param name="showStaticApiState">Static suffix in URL; usually leave empty</param>
        /// <returns></returns>
        public static string GetNcfApiClientPath(string xncfName, string appServiceName, string methodName, string showStaticApiState = null)
        {
            var globalName = ApiBindAttribute.GetGlobalName(xncfName, $"{appServiceName}.{methodName}");

            var indexOfApiGroupDot = globalName.IndexOf(".");
            var apiName = globalName.Substring(indexOfApiGroupDot + 1, globalName.Length - indexOfApiGroupDot - 1);

            var apiPath = WebApiEngine.GetApiPath(xncfName, appServiceName, apiName, showStaticApiState);
            return apiPath;
        }


        /// <summary>
        /// Get the unified default XNCF name used by Aspire
        /// </summary>
        /// <param name="name"></param>
        /// <param name="uniqueCode"></param>
        /// <returns></returns>
        public static string GetXncfProjectName(string name, string uniqueCode = null)
        {
            name = name.Replace(".", "-").Replace("_", "-");
            if (!uniqueCode.IsNullOrEmpty())
            {
                name += $"_{uniqueCode}";
            }
            return name;
        }

        /// <summary>
        /// Get the unified default XNCF name used by Aspire
        /// </summary>
        /// <param name="projectType"></param>
        /// <param name="uniqueCode"></param>
        /// <returns></returns>
        public static string GetXncfProjectName(Type projectType, string uniqueCode = null)
        {
            var name = projectType.Name;
            return GetXncfProjectName(name, uniqueCode);
        }


        /// <summary>
        /// Get the unified default XNCF name used by Aspire
        /// </summary>
        /// <param name="uniqueCode"></param>
        /// <returns></returns>
        public static string GetXncfProjectName<T>(string uniqueCode = null)
        {
            var name = typeof(T).Name;
            return GetXncfProjectName(name, uniqueCode);
        }
    }
}
