<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.0.2</Version>
    <PackageReleaseNotes>
      [2026-07-17] v0.0.1 同步上游项目版本并适配统一本地化能力
      1、Dependency update from Senparc.Ncf.UnitTestExtension to 0.3.15-preview.2
      2、Dependency update from Senparc.Xncf.DynamicData to 0.6.0-preview2
      3、同步 DynamicData 0.6.0-preview2 的页面复制兼容性改进
      [2026-07-29] v0.0.2 Dependency update from Senparc.Ncf.UnitTestExtension to 0.3.16-preview.3
</PackageReleaseNotes>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Basic\Senparc.Ncf.UnitTestExtension\Senparc.Ncf.UnitTestExtension.csproj" />
    <ProjectReference Include="..\Senparc.Xncf.DynamicData\Senparc.Xncf.DynamicData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
