<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>0.0.5</Version>
		<PackageReleaseNotes>
		  [2026-07-17] v0.0.1 同步上游项目版本并适配统一本地化能力
		  1、Dependency update from Senparc.Ncf.Database.MySql.Backcup to 0.20.2-preview2
		  2、Dependency update from Senparc.Ncf.Database.MySql to 0.20.2-preview2
		  3、Dependency update from Senparc.Ncf.Database.Oracle to 0.10.2-preview2
		  4、Dependency update from Senparc.Ncf.Database.PostgreSQL to 0.13.2-preview2
		  5、Dependency update from Senparc.Ncf.Database.SqlServer to 0.20.2-preview2
		  6、Dependency update from Senparc.Ncf.Database.Sqlite to 0.20.2-preview2
		  7、Dependency update from Senparc.Ncf.Database to 0.21.2-preview2
		  8、Dependency update from Senparc.Ncf.DatabasePlant to 0.21.2-preview2
		  [2026-07-29] v0.0.2 Dependency update from Senparc.Ncf.Database.MySql.Backcup to 0.20.3-preview3
		  [2026-07-31] v0.0.3 Dependency update from Senparc.Ncf.Database.MySql to 0.20.4-preview4
		  [2026-08-04] v0.0.4 Dependency updates from upstream projects
		  1、Dependency update from Senparc.Ncf.Database.MySql.Backup to 0.20.5-preview5
		  2、Dependency update from Senparc.Ncf.Database.MySql to 0.20.5-preview5
		  3、Dependency update from Senparc.Ncf.Database.Oracle to 0.10.5-preview5
		  4、Dependency update from Senparc.Ncf.Database.PostgreSQL to 0.13.5-preview5
		  5、Dependency update from Senparc.Ncf.Database.SqlServer to 0.20.5-preview5
		  6、Dependency update from Senparc.Ncf.Database.Sqlite to 0.20.5-preview5
		  7、Dependency update from Senparc.Ncf.Database to 0.21.5-preview5
		  8、Dependency update from Senparc.Ncf.DatabasePlant to 0.21.5-preview5
		  [2026-08-08] v0.0.5 Dependency updates from upstream projects
		  1、Dependency update from Senparc.Ncf.Database.MySql.Backcup to 0.20.6-preview6
		  2、Dependency update from Senparc.Ncf.Database.MySql to 0.20.6-preview6
		  3、Dependency update from Senparc.Ncf.Database.Oracle to 0.10.6-preview6
		  4、Dependency update from Senparc.Ncf.Database.PostgreSQL to 0.13.6-preview6
		  5、Dependency update from Senparc.Ncf.Database.Sqlite to 0.20.6-preview6
		  6、Dependency update from Senparc.Ncf.Database.SqlServer to 0.20.6-preview6
		  7、Dependency update from Senparc.Ncf.DatabasePlant to 0.21.6-preview6
		  8、Dependency update from Senparc.Ncf.Database to 0.21.6-preview6
</PackageReleaseNotes>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.6.1" />
		<PackageReference Include="MSTest.TestFramework" Version="3.6.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Senparc.Ncf.Database.MySql.Backup\Senparc.Ncf.Database.MySql.Backcup.csproj" />
		<ProjectReference Include="..\Senparc.Ncf.Database.MySql\Senparc.Ncf.Database.MySql.csproj" />
		<ProjectReference Include="..\Senparc.Ncf.Database.Oracle\Senparc.Ncf.Database.Oracle.csproj" />
		<ProjectReference Include="..\Senparc.Ncf.Database.PostgreSQL\Senparc.Ncf.Database.PostgreSQL.csproj" />
		<ProjectReference Include="..\Senparc.Ncf.Database.Sqlite\Senparc.Ncf.Database.Sqlite.csproj" />
		<ProjectReference Include="..\Senparc.Ncf.Database.SqlServer\Senparc.Ncf.Database.SqlServer.csproj" />
		<ProjectReference Include="..\Senparc.Ncf.DatabasePlant\Senparc.Ncf.DatabasePlant.csproj" />
		<ProjectReference Include="..\Senparc.Ncf.Database\Senparc.Ncf.Database.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

</Project>
