// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senparc.Xncf.FirmwareUpdate.Models;

#nullable disable

namespace Senparc.Xncf.FirmwareUpdate.Domain.Migrations.Oracle;

[DbContext(typeof(FirmwareUpdateSenparcEntities_Oracle))]
partial class FirmwareUpdateSenparcEntities_OracleModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("Senparc.Xncf.FirmwareUpdate.FirmwareUpdateConfig", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                b.Property<DateTime>("AddTime")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<bool>("AutoMirrorEnabled")
                    .HasColumnType("NUMBER(1)");

                b.Property<string>("AdminRemark")
                    .HasMaxLength(300)
                    .HasColumnType("NVARCHAR2(300)");

                b.Property<bool>("Flag")
                    .HasColumnType("NUMBER(1)");

                b.Property<DateTime?>("LastPeriodicSyncUtc")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<DateTime>("LastUpdateTime")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("Remark")
                    .HasMaxLength(300)
                    .HasColumnType("NVARCHAR2(300)");

                b.Property<int>("TenantId")
                    .HasColumnType("NUMBER(10)");

                b.Property<int>("UpdateIntervalHours")
                    .HasColumnType("NUMBER(10)");

                b.HasKey("Id");

                b.ToTable("Senparc_FirmwareUpdate_FirmwareUpdateConfig");
            });
#pragma warning restore 612, 618
    }
}
