import os

OHS_EN = """[中文版](readme.cn.md)

# Open Host Service (OHS)

In the NCF system, we use the Open Host Service (OHS) pattern from Domain-Driven Design (DDD) for communication between internal modules or domains and with external systems. OHS provides decoupled, integration-friendly communication through public, uniform interfaces (such as APIs and events). OHS has two branches: [Local](Local/readme.md) and [Remote](Remote/readme.md).
"""

LOCAL_EN = """[中文版](readme.cn.md)

# Local branch

The Local branch handles communication between modules or domains within the same system. It exposes interfaces for collaboration while keeping components decoupled and extensible. Local typically runs inside the same system or service without crossing system boundaries.

In Local, `AppService` handles inter-module communication. NCF uses Dynamic WebApi to expose `AppService` methods as Web API endpoints automatically, so you do not need to hand-write Web API services in the Remote branch.
"""

REMOTE_EN = """[中文版](readme.cn.md)

# Remote branch

The Remote branch handles communication with external systems. It integrates through public interfaces (such as RESTful APIs and gRPC) while keeping external systems decoupled and the design extensible. Remote usually involves cross-system or cross-service concerns such as network latency and security.
"""

DOMAIN_EN = """[中文版](readme.cn.md)

# Domain layer

The `Domain` folder contains the core business logic and domain models of the system. These models reflect the core concepts and rules of the business, providing the foundation for the entire system. The `Domain` folder typically contains the following types of components:

- Entity: Business objects with unique identifiers whose attributes and behavior change over time.
- Value Object: Business objects without unique identifiers, used to represent characteristics of concepts or entities, with immutable attributes.
- Aggregate: A group of related objects composed of entities and value objects, persisted and transacted as a whole.
- Aggregate Root: The entry point of an aggregate, responsible for maintaining the integrity and consistency of the aggregate.
- Domain Service: Encapsulates business logic operations that typically do not belong to a single entity or value object.
- Domain Event: Represents important business events that occur in the domain, used for decoupling and tracking business changes.

During development, ensure that core business logic and domain models are placed in the `Domain` folder to maintain code clarity and maintainability.

## Domain folder structure

In the `Domain` folder, we create three default subfolders: `Migrations`, `Models`, and `Services`, to organize different types of domain components.

### Migrations folder

The `Migrations` folder stores database migration files related to domain models. These files apply domain model changes to the database to keep the database structure in sync with the domain models.

Typically, this folder is auto-generated by the XncfBuilder module and manual modification is not recommended.

### Models folder

The `Models` folder stores domain model components such as entities, value objects, aggregates, and aggregate roots. These components reflect the core concepts and rules of the business, forming the foundation of the system.

### Services folder

The `Services` folder stores domain services, domain events, and other business logic operations. These operations typically do not belong to a single entity or value object, but involve interactions between multiple domain model components.

Please ensure that during development, different types of domain components are placed in the appropriate subfolders to maintain code clarity and maintainability.
"""

OHS_PATHS = [
    r"src\Extensions\Senparc.Xncf.AgentsManager\OHS\readme.md",
    r"src\Extensions\Senparc.Xncf.DynamicData\OHS\readme.md",
    r"src\Extensions\Senparc.Xncf.FileManager\OHS\readme.md",
    r"src\Extensions\Senparc.Xncf.KnowledgeBase\OHS\readme.md",
    r"src\Extensions\Senparc.Xncf.MCP\OHS\readme.md",
    r"src\Extensions\Senparc.Xncf.SenMapic\OHS\readme.md",
    r"src\Extensions\Senparc.Xncf.XncfBuilder\Senparc.Xncf.XncfBuilder.Template\templates\template1\OHS\readme.md",
    r"tools\NcfSimulatedSite\Template_OrgName.Xncf.Template_XncfName\OHS\readme.md",
]

LOCAL_PATHS = [p.replace(r"\OHS\readme.md", r"\OHS\Local\readme.md") for p in OHS_PATHS]
REMOTE_PATHS = [p.replace(r"\OHS\readme.md", r"\OHS\Remote\readme.md") for p in OHS_PATHS]

DOMAIN_PATHS = [
    r"src\Extensions\Senparc.Xncf.FileManager\Domain\readme.md",
    r"src\Extensions\Senparc.Xncf.KnowledgeBase\Domain\readme.md",
    r"src\Extensions\Senparc.Xncf.MCP\Domain\readme.md",
    r"src\Extensions\Senparc.Xncf.SenMapic\Domain\readme.md",
    r"src\Extensions\Senparc.Xncf.XncfBuilder\Senparc.Xncf.XncfBuilder.Template\templates\template1\Domain\readme.md",
    r"tools\NcfSimulatedSite\Template_OrgName.Xncf.Template_XncfName\Domain\readme.md",
]


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for path_list, content in [
        (OHS_PATHS, OHS_EN),
        (LOCAL_PATHS, LOCAL_EN),
        (REMOTE_PATHS, REMOTE_EN),
        (DOMAIN_PATHS, DOMAIN_EN),
    ]:
        for rel in path_list:
            path = os.path.join(root, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(path)


if __name__ == "__main__":
    main()
