/*----------------------------------------------------------------
    Copyright (C) 2026 Senparc

    文件名：20260918120000_AddAliasAndExtraPorts.Designer.cs
    文件功能描述：数据库迁移与模型快照


    创建标识：Senparc - 20260918

    修改标识：Senparc - 20260918
    修改描述：v0.3.3 增加沙箱会话别名与附加端口映射列

----------------------------------------------------------------*/

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senparc.Xncf.Sandbox.Models;

#nullable disable

namespace Senparc.Xncf.Sandbox.Domain.Migrations.MySql
{
    [DbContext(typeof(SandboxSenparcEntities_MySql))]
    [Migration("20260918120000_AddAliasAndExtraPorts")]
    partial class AddAliasAndExtraPorts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

                        modelBuilder.Entity("Senparc.Xncf.Sandbox.Domain.Models.DatabaseModel.SandboxSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AccessUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Alias")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");


                    b.Property<double>("CpuLimit")
                        .HasColumnType("double");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExtraPorts")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");


                    b.Property<bool>("Flag")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("HostPort")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MemoryMb")
                        .HasColumnType("int");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RuntimeHandle")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("RuntimeKind")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Status");

                    b.ToTable("Senparc_Sandbox_SandboxSession");
                });
#pragma warning restore 612, 618
        }
    }
}
